name: it_can_cook
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  http: ^1.2.1
  meta: ^1.11.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  intl: any
  date_picker_timeline: ^1.2.5
  loader_overlay: ^4.0.0
  sprintf: ^7.0.0
  cached_network_image: ^3.3.1
  numberpicker: ^2.1.2
  uuid: ^4.4.2
  diacritic: ^0.1.5
  geolocator: ^12.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/onboarding/
    - assets/images/login/
    - assets/images/flag/
    - assets/images/weekly-demo/
    - assets/images/dishesdemo/
    - assets/images/ingredientdemo/
    - assets/images/stepsdemo/
flutter_intl:
  enabled: true
